// Code generated by "marker -method IsJNode -type JValue,JObject,JPair,JArray -output ast_jnode_marker_generated.go"; DO NOT EDIT.

package jsonast

func (*JValue) IsJNode()  {}
func (*JObject) IsJNode() {}
func (*JPair) IsJNode()   {}
func (*JArray) IsJNode()  {}
