// Code generated by "marker -method IsNode -type Value,Object,Pair,Array -output ast_node_marker_generated.go"; DO NOT EDIT.

package jsonast

func (*Value) IsNode()  {}
func (*Object) IsNode() {}
func (*Pair) IsNode()   {}
func (*Array) IsNode()  {}
